services:
  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: development
      APP_HOST:
      APP_PORT: 33000
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: local_library
    image: mdn-express-locallibrary-dev
    networks:
      - default
    ports:
      - 33000:33000
    user: node
    tty: true
    volumes:
      - type: bind
        source: ..
        target: /home/node/mdn-express-locallibrary
    working_dir: /home/node/mdn-express-locallibrary

  db:
    image: mongo:5
    networks:
      - default
    volumes:
      - type: volume
        source: db-data
        target: /data/db

networks:
  default:

volumes:
  db-data:
