services:
  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: development
      HOST:
      PORT: 3000
      DB_ATLAS: "FALSE"
      DB_USER:
      DB_PASS:
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: local_library
    image: mdn-express-locallibrary-dev
    networks:
      - default
    ports:
      - 33000:3000
    user: node
    tty: true
    volumes:
      - type: bind
        source: ..
        target: /home/node/mdn-express-locallibrary
    working_dir: /home/node/mdn-express-locallibrary

  db:
    image: mongo:5
    networks:
      - default
    ports:
      - 37017:27017
    volumes:
      - type: volume
        source: db-data
        target: /data/db

networks:
  default:

volumes:
  db-data:
