services:
  app:
    build: .
    container_name: mdn-express-locallibrary-app-dev
    depends_on:
      - db
    environment:
      NODE_ENV: development
      APP_HOST:
      APP_PORT: 33000
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: local_library
    image: mdn-express-locallibrary-dev
    networks:
      - mdn-express-locallibrary-dev
    ports:
      - 33000:33000
    tty: true
    volumes:
      - type: bind
        source: ..
        target: /home/node/mdn-express-locallibrary
    working_dir: /home/node/mdn-express-locallibrary

  db:
    container_name: mdn-express-locallibrary-db-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    image: mongo:5
    networks:
      - mdn-express-locallibrary-dev
    volumes:
      - type: volume
        source: mdn-express-locallibrary-db-dev
        target: /data/db

networks:
  mdn-express-locallibrary-dev:

volumes:
  mdn-express-locallibrary-db-dev:
